pipeline {
    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            agent {
            docker {
                image 'openjdk:8u131-alpine'
                args '-v /var/run/docker.sock:/var/run/docker.sock'
                    }
            }
            steps {
                sh 'docker build -t java_project .'
                sh 'docker run -d -p 8081:8080 java_project'
            }
        }
    }
}
